spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/xml
    cache: false
  datasource:
    url: jdbc:mysql://192.168.29.112:3306/test?useUnicode=true&characterEncoding=utf8
    username: guoyigps
    password: guoyigps
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico"
  #mybatis
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/**Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: /pojo.**
    global-config:
      db-config:
        id-type: AUTO
logging:
  level:
    com:
      example:
        dao:
          debug
server:
  port: 9090