spring:
  profiles:
    active: @profileActive@

  #mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/com/example/dao/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.dao.pojo.*
  global-config:
    db-config:
      id-type: AUTO
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com:
      example:
        dao:
          debug
server:
  port: 9090


